# Generated by Django 6.0.7 on 2026-07-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('protocol', models.CharField(default='RTSP', max_length=30)),
                ('endpoint', models.CharField(max_length=500)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=80)),
                ('protocol', models.CharField(default='HTTP', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('isp', models.CharField(blank=True, max_length=150, null=True)),
                ('asn', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='online', max_length=20)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('last_check', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
