# Generated by Django 5.2.16 on 2026-07-22 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('node_down', 'Nodo Caído'), ('node_up', 'Nodo Recuperado'), ('latency_high', 'Latencia Alta'), ('latency_normal', 'Latencia Normal'), ('packet_loss', 'Pérdida de Paquetes'), ('status_change', 'Cambio de Estado'), ('camera_offline', 'Cámara Desconectada'), ('camera_online', 'Cámara Reconectada'), ('system', 'Evento de Sistema')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Advertencia'), ('critical', 'Crítico'), ('resolved', 'Resuelto')], default='info', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('details_json', models.TextField(blank=True, default='', help_text='Datos adicionales en formato JSON')),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='monitoring.targetnode')),
            ],
            options={
                'verbose_name': 'Evento de Monitoreo',
                'verbose_name_plural': 'Eventos de Monitoreo',
                'ordering': ['-created_at'],
            },
        ),
    ]
