# Generated by Django 6.0.7 on 2026-07-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_monitoringevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetnode',
            name='last_status_change',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
