# Generated by Django 5.2.16 on 2026-07-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('abuseipdb', 'AbuseIPDB - Reputación de IP & Amenazas'), ('shodan', 'Shodan - Infraestructura Expuesta'), ('hibp', 'Have I Been Pwned - Auditoría de Fugas')], max_length=30, unique=True)),
                ('api_key', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clave de API OSINT',
                'verbose_name_plural': 'Claves de API OSINT',
            },
        ),
        migrations.CreateModel(
            name='SlaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, default='', max_length=200)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración SLA',
                'verbose_name_plural': 'Configuraciones SLA',
            },
        ),
        migrations.CreateModel(
            name='SystemParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping_interval', models.IntegerField(default=5, help_text='Intervalo de ping en segundos')),
                ('event_retention_days', models.IntegerField(default=30, help_text='Días de retención de eventos')),
                ('notification_sound', models.CharField(choices=[('beep', 'Beep estándar'), ('siren', 'Sirena Táctica Cyberpunk'), ('mute', 'Silencioso')], default='beep', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetros del Sistema',
                'verbose_name_plural': 'Parámetros del Sistema',
            },
        ),
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, default='', max_length=255)),
                ('chat_id', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Telegram',
                'verbose_name_plural': 'Configuraciones Telegram',
            },
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('pagerduty', 'PagerDuty'), ('jira', 'Jira / Atlassian'), ('generic', 'Webhook Genérico')], max_length=30, unique=True)),
                ('endpoint_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
            },
        ),
    ]
