# Generated by Django 6.0.7 on 2026-07-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OsintQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(max_length=50)),
                ('query_term', models.CharField(max_length=255)),
                ('result_json', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
